// ============================================================
// USMA — App Localization Service
// app_localization.dart
//
// Structured Multilingual Localization (English, Hindi, Odia, Santali Ol Chiki, Gondi, Bhili)
// Supporting core student screens:
//   - Bottom Navigation (MainScaffold)
//   - Settings Screen
//   - Dashboard Screen
// ============================================================

class AppLocalization {
  static const String langEnglish = 'en';
  static const String langHindi = 'hi';
  static const String langOdia = 'or';
  static const String langSantali = 'sat';
  static const String langGondi = 'gon';
  static const String langBhili = 'bhb';

  static const List<String> supportedLanguages = [
    langEnglish,
    langHindi,
    langOdia,
    langSantali,
    langGondi,
    langBhili,
  ];

  static const Map<String, String> languageNames = {
    'en': 'English',
    'hi': 'हिन्दी (Hindi)',
    'or': 'ଓଡ଼ିଆ (Odia)',
    'sat': 'ᱥᱟᱱᱛᱟᱲᱤ (Santali - Ol Chiki)',
    'gon': 'Gondi (गोंडी)',
    'bhb': 'Bhili (भीली)',
  };

  static const Map<String, String> languageCodeFromDisplay = {
    'English': 'en',
    'हिन्दी (Hindi)': 'hi',
    'ଓଡ଼ିଆ (Odia)': 'or',
    'ᱥᱟᱱᱛᱟᱲᱤ (Santali - Ol Chiki)': 'sat',
    'Gondi (गोंडी)': 'gon',
    'Bhili (भीली)': 'bhb',
  };

  static const Map<String, Map<String, String>> _strings = {
    langEnglish: {
      'nav_home': 'Home',
      'nav_schemes': 'Scholarships',
      'nav_wallet': 'Documents',
      'nav_dbt': 'Payments',
      'nav_saathi': 'JAGO Help',

      'settings_title': 'App Settings',
      'settings_accessibility': 'Accessibility & Language',
      'settings_display_language': 'App Display Language',
      'settings_dark_mode': 'Dark Mode',
      'settings_dark_mode_sub': 'Reduce glare in low-light conditions',
      'settings_about': 'About Ministry Portal',
      'settings_version': 'Application Version',
      'settings_version_val': 'USMA v1.0.0+1 (Ministry Production Build)',
      'settings_terms': 'Terms & Ministry Guidelines',
      'settings_terms_val': 'Ministry of Tribal Affairs • Government of India',
      'settings_coverage_notice': 'Multilingual Coverage Notice',
      'settings_coverage_desc': 'Translated screens: Navigation, Settings, Dashboard, and JAGO AI Assistant.',

      'dash_welcome': 'Welcome back',
      'dash_summary_greeting': 'Here is your scholarship summary.',
      'dash_attention_title': 'Needs Your Attention',
      'dash_attention_empty': 'Everything looks good! No actions required right now.',
      'dash_active_scholarship': 'My Active Scholarship',
      'dash_recent_payment': 'Recent Payment',
      'dash_quick_actions': 'Quick Actions',
      'dash_unified_verification': 'Unified Verification',
      'dash_unified_verification_sub': 'Multi-Source Status',
      'dash_officer_analytics': 'Officer Analytics',
      'dash_officer_analytics_sub': 'Coverage Gap Matrix',
      'dash_statutory_check': 'Statutory Rule Check',
      'dash_eligibility_engine': 'Eligibility Engine',
      'dash_apply_scholarship': 'Apply for Scholarship',
      'dash_explore_schemes': 'Explore all 5 MoTA programs',
      'dash_active_applications': 'Active Applications',
      'dash_dbt_tracker': 'Payment Tracker',
      'dash_deficiency_center': 'Deficiency Center',
      'dash_action_required': 'Action Required',
      'dash_recommended_schemes': 'Recommended Schemes for You',
    },
    langHindi: {
      'nav_home': 'मुख्य पृष्ठ',
      'nav_schemes': 'छात्रवृत्तियां',
      'nav_wallet': 'दस्तावेज़',
      'nav_dbt': 'भुगतान',
      'nav_saathi': 'जागो सहायता',

      'settings_title': 'ऐप सेटिंग्स',
      'settings_accessibility': 'सुगमता एवं भाषा',
      'settings_display_language': 'ऐप प्रदर्शन भाषा',
      'settings_dark_mode': 'डार्क मोड',
      'settings_dark_mode_sub': 'कम रोशनी में आंखों के तनाव को कम करें',
      'settings_about': 'मंत्रालय पोर्टल के बारे में',
      'settings_version': 'एप्लिकेशन संस्करण',
      'settings_version_val': 'यूएसएमए v1.0.0+1 (मंत्रालय प्रोडक्शन संस्करण)',
      'settings_terms': 'नियम एवं मंत्रालय दिशानिर्देश',
      'settings_terms_val': 'जनजातीय कार्य मंत्रालय • भारत सरकार',
      'settings_coverage_notice': 'बहुभाषी कवरेज सूचना',
      'settings_coverage_desc': 'अनुवादित स्क्रीन: नेविगेशन, सेटिंग्स, डैशबोर्ड, और जागो AI सहायक।',

      'dash_welcome': 'वापसी पर स्वागत है',
      'dash_summary_greeting': 'यहाँ आपकी छात्रवृत्ति का सारांश है।',
      'dash_attention_title': 'आपके ध्यान की आवश्यकता है',
      'dash_attention_empty': 'सब कुछ ठीक है! अभी किसी कार्रवाई की आवश्यकता नहीं है।',
      'dash_active_scholarship': 'मेरी सक्रिय छात्रवृत्ति',
      'dash_recent_payment': 'हाल का भुगतान',
      'dash_quick_actions': 'त्वरित कार्य',
      'dash_unified_verification': 'एकीकृत सत्यापन',
      'dash_unified_verification_sub': 'बहु-स्रोत स्थिति',
      'dash_officer_analytics': 'अधिकारी एनालिटिक्स',
      'dash_officer_analytics_sub': 'कवरेज अंतर मैट्रिक्स',
      'dash_statutory_check': 'वैधानिक नियम जांच',
      'dash_eligibility_engine': 'पात्रता इंजन',
      'dash_apply_scholarship': 'छात्रवृत्ति के लिए आवेदन करें',
      'dash_explore_schemes': 'सभी 5 MoTA कार्यक्रमों को देखें',
      'dash_active_applications': 'सक्रिय आवेदन',
      'dash_dbt_tracker': 'भुगतान ट्रैकर',
      'dash_deficiency_center': 'कमी निवारण केंद्र',
      'dash_action_required': 'कार्रवाई आवश्यक',
      'dash_recommended_schemes': 'आपके लिए अनुशंसित योजनाएं',
    },
    langOdia: {
      'nav_home': 'ମୁଖ୍ୟ ପୃଷ୍ଠା',
      'nav_schemes': 'ଛାତ୍ରବୃତ୍ତି',
      'nav_wallet': 'ଦସ୍ତାବିଜ',
      'nav_dbt': 'ପେମେଣ୍ଟ୍',
      'nav_saathi': 'ଜାଗୋ ସହାୟତା',

      'settings_title': 'ଆପ୍ ସେଟିଙ୍ଗ୍ସ',
      'settings_accessibility': 'ସୁବିଧା ଓ ଭାଷା',
      'settings_display_language': 'ଆପ୍ ପ୍ରଦର୍ଶନ ଭାଷା',
      'settings_dark_mode': 'ଡାର୍କ ମୋଡ୍',
      'settings_dark_mode_sub': 'ଅଳ୍ପ ଆଲୋକରେ ଆଖିର ଚାପ ହ୍ରାସ କରନ୍ତୁ',
      'settings_about': 'ମନ୍ତ୍ରଣାଳୟ ପୋର୍ଟାଲ୍ ବିଷୟରେ',
      'settings_version': 'ଆପ୍ଲିକେସନ୍ ସଂସ୍କରଣ',
      'settings_version_val': 'USMA v1.0.0+1 (ମନ୍ତ୍ରଣାଳୟ ପ୍ରଡକ୍ସନ୍ ବିଲ୍ଡ)',
      'settings_terms': 'ନିୟମାବଳୀ ଓ ମନ୍ତ୍ରଣାଳୟ ମାର୍ଗଦର୍ଶିକା',
      'settings_terms_val': 'ଆଦିବାସୀ ବ୍ୟାପାର ମନ୍ତ୍ରଣାଳୟ • ଭାରତ ସରକାର',
      'settings_coverage_notice': 'ବହୁଭାଷୀ କଭରେଜ୍ ସୂଚନା',
      'settings_coverage_desc': 'ଅନୁବାଦିତ ପୃଷ୍ଠା: ନେଭିଗେସନ୍, ସେଟିଙ୍ଗ୍ସ, ଡ୍ୟାସବୋର୍ଡ, ଏବଂ ଜାଗୋ AI ସହାୟକ।',

      'dash_welcome': 'ସ୍ୱାଗତମ୍',
      'dash_summary_greeting': 'ଏଠାରେ ଆପଣଙ୍କ ଛାତ୍ରବୃତ୍ତି ସାରାଂଶ ଅଛି।',
      'dash_attention_title': 'ଆପଣଙ୍କ ଧ୍ୟାନ ଆବଶ୍ୟକ',
      'dash_attention_empty': 'ସବୁକିଛି ଠିକ୍ ଅଛି! ବର୍ତ୍ତମାନ କୌଣସି ପଦକ୍ଷେପ ଆବଶ୍ୟକ ନାହିଁ।',
      'dash_active_scholarship': 'ମୋର ସକ୍ରିୟ ଛାତ୍ରବୃତ୍ତି',
      'dash_recent_payment': 'ସମ୍ପ୍ରତି ପେମେଣ୍ଟ୍',
      'dash_quick_actions': 'ଦ୍ରୁତ କାର୍ଯ୍ୟାନୁଷ୍ଠାନ',
      'dash_unified_verification': 'ଏକୀକୃତ ଯାଞ୍ଚ',
      'dash_unified_verification_sub': 'ବହୁ-ଉତ୍ସ ସ୍ଥିତି',
      'dash_officer_analytics': 'ଅଧିକାରୀ ଆନାଲିଟିକ୍ସ',
      'dash_officer_analytics_sub': 'କଭରେଜ୍ ଅନ୍ତର ମ୍ୟାଟ୍ରିକ୍ସ',
      'dash_statutory_check': 'ସରକାରୀ ନିୟମ ଯାଞ୍ଚ',
      'dash_eligibility_engine': 'ଯୋଗ୍ୟତା ଇଞ୍ଜିନ୍',
      'dash_apply_scholarship': 'ଛାତ୍ରବୃତ୍ତି ପାଇଁ ଆବେଦନ କରନ୍ତୁ',
      'dash_explore_schemes': 'ସମସ୍ତ ୫ଟି MoTA କାର୍ଯ୍ୟକ୍ରମ ଦେଖନ୍ତୁ',
      'dash_active_applications': 'ସକ୍ରିୟ ଆବେଦନ',
      'dash_dbt_tracker': 'ପେମେଣ୍ଟ୍ ଟ୍ରାକର୍',
      'dash_deficiency_center': 'ତ୍ରୁଟି ସଂଶୋଧନ କେନ୍ଦ୍ର',
      'dash_action_required': 'ପଦକ୍ଷେପ ଆବଶ୍ୟକ',
      'dash_recommended_schemes': 'ଆପଣଙ୍କ ପାଇଁ ସୁପାରିଶ କରାଯାଇଥିବା ଯୋଜନା',
    },
    langSantali: {
      'nav_home': 'ᱚᱲᱟᱜ (Home)',
      'nav_schemes': ' আঁচᱷ (Schemes)',
      'nav_wallet': 'ᱛᱷᱚᱞᱤ (Wallet)',
      'nav_dbt': 'DBT (ᱴᱟᱠᱟ)',
      'nav_saathi': 'ᱡᱟᱜᱚ AI',

      'settings_title': 'ᱮᱯ ᱥᱟᱡᱟᱣ (Settings)',
      'settings_accessibility': 'ᱯᱟᱹᱨᱥᱤ ᱟᱨ ᱥᱩᱵᱤᱫᱷᱟ',
      'settings_display_language': 'ᱩᱫᱩᱜ ᱯᱟᱹᱨᱥᱤ',
      'settings_dark_mode': 'ᱧᱩᱛ ᱢᱚᱰ',
      'settings_dark_mode_sub': 'ᱢᱮᱫ ᱨᱮᱭᱟᱜ ᱠᱚᱥᱴᱚ ᱠᱚᱢᱟᱣ',
      'settings_about': 'ᱢᱚᱱᱛᱨᱟᱞᱚᱭ ᱵᱟᱵᱚᱛ',
      'settings_version': 'ᱮᱯ ᱵᱷᱟᱨᱥᱚᱱ',
      'settings_version_val': 'USMA v1.0.0+1',
      'settings_terms': 'ᱱᱤᱭᱚᱢ ᱟᱨ ᱫᱤᱥᱟᱹ ᱩᱫᱩᱜ',
      'settings_terms_val': 'ᱡᱟᱱᱡᱟᱛᱤᱭᱟᱹ ᱠᱟᱹᱢᱤ ᱢᱚᱱᱛᱨᱟᱞᱚᱭ • ᱵᱷᱟᱨᱚᱛ ᱥᱚᱨᱠᱟᱨ',
      'settings_coverage_notice': 'ᱥᱟᱱᱛᱟᱲᱤ ᱚᱞ ᱪᱤᱠᱤ ᱩᱫᱩᱜ',
      'settings_coverage_desc': 'ᱱᱚᱣᱟ ᱫᱚ ᱥᱟᱱᱛᱟᱲᱤ ᱚᱞ ᱪᱤᱠᱤ ᱛᱮ ᱛᱚᱨᱡᱚᱢᱟ ᱠᱟᱱᱟ (Draft).',

      'dash_welcome': 'ᱡᱚᱦᱟᱨ',
      'dash_quick_actions': 'ᱞᱚᱜᱚᱱ ᱠᱟᱹᱢᱤ',
      'dash_unified_verification': 'ᱡᱚᱛᱚ ᱡᱟᱭᱜᱟ ᱨᱮᱭᱟᱜ ᱯᱚᱨᱢᱟᱬ',
      'dash_unified_verification_sub': 'Multi-Source Status',
      'dash_officer_analytics': 'ᱚᱯᱷᱤᱥᱚᱨ ᱠᱟᱹᱢᱤ',
      'dash_officer_analytics_sub': 'Coverage Gap Matrix',
      'dash_statutory_check': 'ᱱᱤᱭᱚᱢ ᱡᱟᱸᱪ',
      'dash_eligibility_engine': 'ᱡᱚᱜᱽᱭᱚᱛᱟ ᱤᱧᱡᱤᱱ',
      'dash_apply_scholarship': 'ᱥᱠᱚᱞᱟᱨᱥᱤᱯ ᱞᱟᱹᱜᱤᱫ ᱫᱚᱨᱠᱷᱟᱥᱛ',
      'dash_explore_schemes': 'ᱢᱚᱬᱮ ᱜᱚᱴᱟᱝ MoTA ᱠᱟᱹᱢᱤᱦᱚᱨᱟ',
      'dash_active_applications': 'ᱪᱟᱹᱞᱩ ᱟᱠᱟᱱ ᱫᱚᱨᱠᱷᱟᱥᱛ',
      'dash_dbt_tracker': 'DBT ᱴᱨᱟᱠᱚᱨ',
      'dash_deficiency_center': 'ᱠᱷᱟᱹᱢᱛᱤ ᱥᱩᱫᱷᱨᱟᱹᱣ ᱴᱷᱟᱶ',
      'dash_action_required': 'ᱠᱟᱹᱢᱤ ᱞᱟᱹᱠᱛᱤ ᱢᱮᱱᱟᱜ-ᱟ',
      'dash_recommended_schemes': 'ᱟᱢ ᱞᱟᱹᱜᱤᱫ ᱥᱠᱤᱢ',
    },
    langGondi: {
      'nav_home': 'घर (Home)',
      'nav_schemes': 'योजना (Schemes)',
      'nav_wallet': 'बटुआ (Wallet)',
      'nav_dbt': 'DBT (रुपया)',
      'nav_saathi': 'जागो AI',

      'settings_title': 'ऐप सेटिंग्स',
      'settings_accessibility': 'गोंडी भाषा एवं सुगमता (Unreviewed)',
      'settings_display_language': 'भाषा चुनिए',
      'settings_dark_mode': 'डार्क मोड',
      'settings_dark_mode_sub': 'आँख के सुरक्षा',
      'settings_about': 'मंत्रालय बारे में',
      'settings_version': 'वर्जन',
      'settings_version_val': 'USMA v1.0.0+1',
      'settings_terms': 'नियम',
      'settings_terms_val': 'जनजातीय कार्य मंत्रालय',
      'settings_coverage_notice': 'गोंडी भाषा सूचना',
      'settings_coverage_desc': 'गोंडी भाषा अनुवाद समीक्षाधीन है (Needs community review).',

      'dash_welcome': 'सेवा जोहार',
      'dash_quick_actions': 'जल्दी काम',
      'dash_unified_verification': 'सत्यापन',
      'dash_unified_verification_sub': 'सब स्रोत से जांच',
      'dash_officer_analytics': 'अधिकारी विश्लेषण',
      'dash_officer_analytics_sub': 'अंतर विश्लेषण',
      'dash_statutory_check': 'नियम जांच',
      'dash_eligibility_engine': 'पात्रता जांच',
      'dash_apply_scholarship': 'छात्रवृत्ति अर्जी',
      'dash_explore_schemes': '5 योजना देखो',
      'dash_active_applications': 'चालू अर्जी',
      'dash_dbt_tracker': 'DBT खाता',
      'dash_deficiency_center': 'सुधार केंद्र',
      'dash_action_required': 'काम जरूरी',
      'dash_recommended_schemes': 'आपके योजना',
    },
    langBhili: {
      'nav_home': 'घर (Home)',
      'nav_schemes': 'योजना (Schemes)',
      'nav_wallet': 'झोली (Wallet)',
      'nav_dbt': 'DBT',
      'nav_saathi': 'जागो AI',

      'settings_title': 'सेटिंग',
      'settings_accessibility': 'भीली भाषा (Unreviewed)',
      'settings_display_language': 'भाषा',
      'settings_dark_mode': 'काळो मोड',
      'settings_dark_mode_sub': 'आँख बचाओ',
      'settings_about': 'मंत्रालय',
      'settings_version': 'वर्जन',
      'settings_version_val': 'USMA v1.0.0+1',
      'settings_terms': 'नियम',
      'settings_terms_val': 'जनजातीय कार्य मंत्रालय',
      'settings_coverage_notice': 'भीली सूचना',
      'settings_coverage_desc': 'भीली भाषा अनुवाद समीक्षाधीन है (Needs community review).',

      'dash_welcome': 'राम राम',
      'dash_quick_actions': 'काम',
      'dash_unified_verification': 'जांच',
      'dash_unified_verification_sub': 'सत्यापन',
      'dash_officer_analytics': 'अधिकारी',
      'dash_officer_analytics_sub': 'गैप',
      'dash_statutory_check': 'नियम',
      'dash_eligibility_engine': 'पात्रता',
      'dash_apply_scholarship': 'अर्जी लगाओ',
      'dash_explore_schemes': '5 योजना',
      'dash_active_applications': 'अर्जी',
      'dash_dbt_tracker': 'पैसा',
      'dash_deficiency_center': 'कमी सुधार',
      'dash_action_required': 'जरूरी काम',
      'dash_recommended_schemes': 'योजना',
    },
  };

  /// Retrieves a localized string by key and language code.
  /// Falls back to English if the translation is not present.
  static String tr(String key, {String lang = langEnglish}) {
    final langMap = _strings[lang] ?? _strings[langEnglish]!;
    return langMap[key] ?? _strings[langEnglish]?[key] ?? key;
  }
}
